name: Build, Test
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18"]
    name: Build using Node.js ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Building
        run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18"]
    name: Test using Node.js ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Testing
        run: npm run test
        env:
          MONGO_URL: mongodb+srv://username:password@clusterone.gcnbb.mongodb.net/?retryWrites=true&w=majority
